#' @title Sample
#' @description
#' A class to represent the sample. It contains all the necessary
#' information about the sample
#' @examples
#' sample <- Sample$new(id = 1, sample_name = "test",
#' sample_type = SampleType$new("TEST"),
#' sample_location = SampleLocation$new(1, 1))
#'
#' @export
Sample <- R6::R6Class(
  "Sample",
  list(
    #' @field id Sample id, when reading from a plate it is a id extracted from
    #' the sample position on the plate
    id = NA,
    #' @field sample_name Sample name
    sample_name = NULL,

    #' @field sample_type A sample type - is the sample used for testing,
    #' is it blank, positive or negative control
    sample_type = NULL,

    #' @field sample_location Position on the Plate
    sample_location = NULL,

    #' @field warnings list of warnings warnings are read from the file or
    #' generated during the reading process
    warnings = list(),

    #' @field errors lit of errors; errors are read from the file or
    #' generated during the reading process
    errors = list(),

    #' @field data The dataframe containing information about the analytes within the sample.
    #' The dataframe rows are different measures, such as `Median`, `Net MFI`, etc. 
    #'  whereas the columns represent different analytes
    #'
    data = data.frame(),


    #' @description
    #' Initializes the sample object
    #'
    #' @param id (`numeric(1)`)\cr
    #' The id of the sample - usually just the sample row number,
    #' can be derived from the sample location
    #'
    #' @param sample_name (`character(1)`)\cr
    #' The name of the sample
    #'
    #' @param sample_type (`SampleType`)\cr
    #' The type of the sample
    #'
    #' The location of the sample on the plate
    #'
    #' @param warnings (`list`)\cr
    #' List containing all the warnings connected to the sample -
    #' generated by the validity checks or read from file
    #' @param errors (`list`)\cr
    #' List containing all the critical errors connected to the sample -
    #' generated by the validity checks or read from file
    #'
    #' @param data (`data.frame`)\cr
    #' The dataframe containing the information about analytes within the sample
    #'
    initialize = function(id,
                          sample_name,
                          sample_type = NULL,
                          sample_location = NULL,
                          warnings = list(),
                          errors = list(),
                          data = data.frame()) {
      # check for valid input
      stopifnot(length(id) == 1 && is.numeric(id))
      stopifnot(length(sample_name) == 1 &&
        is.character(sample_name))

      stopifnot(is.null(sample_type) ||
        "SampleType" %in% class(sample_type))
      stopifnot(is.null(sample_location) ||
        "SampleLocation" %in% class(sample_location))
      stopifnot(is.data.frame(data))

      self$id <- id
      self$sample_name <- sample_name
      if (is.null(sample_type)) {
        self$sample_type <- SampleType$new()
      } else {
        self$sample_type <- sample_type
      }
      if (is.null(sample_location)) {
        self$sample_location <- SampleLocation$new()
      } else {
        self$sample_location <- sample_location
      }

      # check if data is all numeric
      all_numeric <- all(sapply(data, is.numeric))
      if (!all_numeric) {
        data_num <- as.data.frame(matrix(ncol = ncol(data), nrow = nrow(data)))
        colnames(data_num) <- colnames(data)
        rownames(data_num) <- rownames(data)

        # fix conversion TODO
        for (i in seq_len(ncol(data))) {
          data_num[, i] <- as.numeric(as.character(data[, i]))
        }

        rownames(data_num) <- rownames(data)
        colnames(data_num) <- colnames(data)
        data <- data_num
      }

      self$warnings <- warnings
      self$errors <- errors

      self$data <- data
    },

    #' @description
    #' Prints the sample information
    print = function(...) {
      cat("A sample", self$sample_name, "with ID: ", self$id, "\n")
      self$sample_type$print()
      self$sample_location$print()

      invisible(self)
    },

    #' @description
    #' Joins the data of two samples
    #' @param new_sample (`Sample`)\cr
    #' A new sample to be merged with the current sample
    #'
    #' @return The updated sample object -
    join = function(new_sample) {
      if (!verify_numeric_join(self$id, new_sample$id)) {
        stop("Cannot join samples of different IDs")
      }
      self$id <- get_join_value(self$id, new_sample$id)

      self$sample_type$join(new_sample$sample_type)
      self$sample_location$join(new_sample$sample_location)


      self$data <- dplyr::bind_rows(self$data, new_sample$data)
    }
  )
)